server:
  port: 8080
  
#Database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-manager
    username: alex
    password: alex
  jpa:
    hibernate:
      ddl-auto: update

#Jasypt
jasypt:
  password: tGlirw6[<sqooq:8;lfT;J%ota:(zf%K
